# Bash completion for elpacman.
# Generated by `elpacman completions bash'; do not edit by hand.
# shellcheck shell=bash
_elpacman() {
    local cur cword
    _init_completion || return

    local commands="update upgrade install delete remove search info list files outdated check repair recompile autoremove completions version help"

    if [ "${cword}" -eq 1 ]; then
        mapfile -t COMPREPLY < <(compgen -W "${commands}" -- "${cur}")
        return
    fi

    local opts=""
    # `words' is populated by bash-completion's `_init_completion'.
    # shellcheck disable=SC2154
    case "${words[1]}" in
        update)
            opts=""
            ;;
        upgrade)
            opts="-y --yes --assume-yes --vc"
            ;;
        install)
            opts="-y --yes --assume-yes --vc"
            ;;
        delete)
            opts="-y --yes --assume-yes"
            ;;
        remove)
            opts="-y --yes --assume-yes"
            ;;
        search)
            opts=""
            ;;
        info)
            opts=""
            ;;
        list)
            opts=""
            ;;
        files)
            opts=""
            ;;
        outdated)
            opts=""
            ;;
        check)
            opts=""
            ;;
        repair)
            opts="-y --yes --assume-yes"
            ;;
        recompile)
            opts="-y --yes --assume-yes"
            ;;
        autoremove)
            opts="-y --yes --assume-yes"
            ;;
        completions)
            opts=""
            ;;
        version)
            opts=""
            ;;
        help)
            opts=""
            ;;
    esac

    if [ -n "${opts}" ]; then
        mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")
    fi
}
complete -F _elpacman elpacman
